name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Azure
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - Azure

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      VITE_API_URL: ${{ secrets.AZURE_API_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Create .env.production file
        run: |
          cat <<EOF > .env.production
          VITE_API_URL=${{ secrets.AZURE_API_URL }}
          VITE_RAPIDAPI_KEY=${{ secrets.VITE_RAPIDAPI_KEY }}
          VITE_UNSPLASH_ACCESS_KEY=${{ secrets.VITE_UNSPLASH_ACCESS_KEY }}
          VITE_YOUTUBE_API_KEY=${{ secrets.VITE_YOUTUBE_API_KEY }}
          VITE_WEATHER_API_KEY=${{ secrets.VITE_WEATHER_API_KEY }}
          VITE_EMAILJS_SERVICE_ID=${{ secrets.EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID=${{ secrets.EMAILJS_TEMPLATE_ID }}
          VITE_EMAILJS_PUBLIC_KEY=${{ secrets.EMAILJS_PUBLIC_KEY }}
          EOF

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy with SWA CLI
        run: npx @azure/static-web-apps-cli@latest deploy ./dist --deployment-token "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_SAND_0AEF9A403 }}" --env production
